name: Strategy Factory – Generate & Back-test
on:
  workflow_dispatch:           # run manually from Actions-tab

jobs:
  factory:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    # —─────────────────────────── 1. CHECKOUT ──────────────────────────────
    - name: Checkout repo
      uses: actions/checkout@v4

    # —─────────────────────────── 2. PYTHON LAYER ──────────────────────────
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Lean CLI + stubs for local back-tests
        pip install lean quantconnect-stubs

    # —─────────────────────────── 3. CANDIDATE GEN ─────────────────────────
    - name: Generate candidates
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    - name: Ruff lint
      run: |
        ruff check --ignore F403,F405,F841 factory/candidates

    - name: AST future-data check
      run: |
        python factory/scripts/check_future_data.py

    - name: Pytest import check
      run: |
        pytest -q tests                       # compile-only; no execution

    # —─────────────────────────── 4. FREE-UP DISK (GitHub runner limit) ────
    - name: Free runner disk
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android

    # —─────────────────────────── 5. MINIMAL LEAN CONFIG ───────────────────
    # Instead of `lean init --ci`, we just drop a tiny lean.json so CLI is happy
    - name: Create lean.json (CI)
      run: |
        cat > lean.json <<'EOF'
        {
          "version": "2.0.0",
          "data-folder": "data",
          "lean-engine": {
            "image": "quantconnect/lean:latest"
          }
        }
        EOF

    # —─────────────────────────── 6. BACK-TEST LOOP ────────────────────────
    - name: Run Lean back-tests
      run: |
        mkdir -p backtest_reports
        for dir in factory/candidates/ALG_*; do
          echo "── Back-testing $(basename "$dir") ──"
          lean backtest "$dir" \
              --detach \
              --image quantconnect/lean:latest \
              --start 2021-01-01 --end 2023-12-31 \
              --output backtest_reports/$(basename "$dir")
        done

    # —─────────────────────────── 7. PUBLISH ARTEFACTS ─────────────────────
    - name: Upload cleaned candidates
      uses: actions/upload-artifact@v4
      with:
        name: surviving_algorithms
        path: factory/candidates

    - name: Upload back-test reports
      uses: actions/upload-artifact@v4
      with:
        name: backtest_reports
        path: backtest_reports
