name: Strategy Factory – Generate & Back-test

on:
  # Press “Run workflow” in the Actions tab to launch a run
  workflow_dispatch:

  # (Optional) run automatically each day at 06:00 UTC
  schedule:
    - cron: '0 6 * * *'

jobs:
  factory:
    runs-on: ubuntu-latest
    timeout-minutes: 60          # hard cap so a run can’t hang forever

    steps:
    ######################################################################
    # 1 ▸ pull your repo
    ######################################################################
    - name: Checkout repo
      uses: actions/checkout@v4

    ######################################################################
    # 2 ▸ install Python 3.11 and libraries
    ######################################################################
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    ######################################################################
    # 3 ▸ GPT generates candidate strategies
    ######################################################################
    - name: Generate candidates
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    ######################################################################
    # 4 ▸ Static gate (lint → AST → pytest)
    ######################################################################
    - name: Ruff lint
      run: |
        ruff check --ignore F403,F405,F841 factory/candidates

    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    - name: Pytest import check
      run: |
        pytest -q tests

    ######################################################################
    # 5 ▸ Back-test survivors with Lean Docker (foundation image ~5 GB)
    ######################################################################
    - name: Run Lean back-tests
      if: success()
      env:
        LEAN_DOCKER_IMAGE: quantconnect/lean:foundation
      run: |
        mkdir backtest_reports
        for dir in factory/candidates/ALG_*; do
          echo "── Back-testing $dir ──"
          docker run --rm \
            -v ${{ github.workspace }}:/Lean/Launcher \
            -w /Lean/Launcher/$dir \
            ${LEAN_DOCKER_IMAGE} \
            lean backtest "$dir" \
              --start 2021-01-01 --end 2023-12-31 \
              --output ../../../backtest_reports/$(basename $dir).json
        done

    ######################################################################
    # 6 ▸ Upload results for download
    ######################################################################
    - name: Upload cleaned candidates
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: candidates_clean
        path: factory/candidates

    - name: Upload back-test reports
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: backtest_reports
        path: backtest_reports
