name: Strategy Factory – Generate One

on:
  workflow_dispatch:        # lets you press a button to run it

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install openai tiktoken

    - name: Run generator script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py \
               --task "simple RSI strategy"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: candidates
        path: factory/candidates
