name: Strategy Factory – Generate & Back-test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'       # optional daily run

jobs:
  factory:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    # 1 ▸ Checkout repo
    - uses: actions/checkout@v4

    # 2 ▸ Python + deps
    - uses: actions/setup-python@v4
      with: {python-version: '3.11'}

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3 ▸ GPT generation
    - name: Generate candidates
      env: {OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}}
      run: python factory/scripts/generate_algo.py --task "simple RSI strategy"

    # 4 ▸ Static gate
    - name: Ruff lint
      run: ruff check --ignore F403,F405,F841 factory/candidates

    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    - name: Pytest import check
      run: pytest -q tests

    # 5 ▸ Free disk, then pull ***foundation-python*** image
    - name: Prune docker cache
      run: docker system prune -af

    - name: Run Lean back-tests (foundation-python ≈3 GB)
      if: success()
      env:
        LEAN_DOCKER_IMAGE: quantconnect/lean:foundation-python
      run: |
        mkdir backtest_reports
        for dir in factory/candidates/ALG_*; do
          echo "── Back-testing $dir ──"
          docker run --rm \
            -v ${{ github.workspace }}:/Lean/Launcher \
            -w /Lean/Launcher/$dir \
            ${LEAN_DOCKER_IMAGE} \
            lean backtest "$dir" \
              --start 2021-01-01 --end 2023-12-31 \
              --output ../../../backtest_reports/$(basename $dir).json
        done

    # 6 ▸ Upload artifacts
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: candidates_clean
        path: factory/candidates

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: backtest_reports
        path: backtest_reports
