name: Strategy Factory – Generate One

on:
  workflow_dispatch:            # manual button in Actions tab
  schedule:
    - cron: '0 6 * * *'         # optional: daily at 06:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ pull repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2 ▸ Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3 ▸ dependencies
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4 ▸ GPT makes candidates
    - name: Generate candidates
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    # 5 ▸ Ruff lint (ignore common Lean warnings)
    - name: Ruff lint
      run: |
        ruff check --ignore F403,F405,F841 factory/candidates

    # 6 ▸ AST look-ahead guard
    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    # 7 ▸ Import test (ONLY root tests folder)
    - name: Pytest import check
      run: |
        pytest -q tests        # <-- limits discovery to one directory

    # 8 ▸ Upload survivors
    - name: Upload surviving candidates
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: candidates_clean
        path: factory/candidates
