    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate candidates
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    - name: Ruff lint
      run: |
        ruff factory/candidates || (echo "Lint failed" && exit 1)

    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    - name: Pytest import check
      run: |
        pytest -q

    - name: Upload surviving candidates
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: candidates_clean
        path: factory/candidates
