name: Strategy Factory – Generate One

on:
  # Press “Run workflow” in the Actions tab any time
  workflow_dispatch:

  # Optional: run automatically every day at 06:00 UTC
  schedule:
    - cron: '0 6 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ get your repo code onto the runner
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2 ▸ install Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3 ▸ install all required libraries
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4 ▸ call GPT to create strategy folders
    - name: Generate candidates
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    # 5 ▸ lint with Ruff (ignore Lean-style wildcard import warnings)
    - name: Ruff lint
      run: |
        ruff check --ignore F403,F405,F841 factory/candidates

    # 6 ▸ custom AST check for look-ahead bias
    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    # 7 ▸ pytest: can each file import?
    - name: Pytest import check
      run: |
        pytest -q

    # 8 ▸ zip & upload only if every step above succeeded
    - name: Upload surviving candidates
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: candidates_clean
        path: factory/candidates
