name: Strategy Factory – Generate One

on:
  workflow_dispatch:            # click-to-run button in Actions tab
  schedule:
    - cron: '0 6 * * *'         # optional daily run at 06:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate candidates
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python factory/scripts/generate_algo.py --task "simple RSI strategy"

    - name: Ruff lint
      run: |
        ruff factory/candidates

    - name: AST future-data check
      run: |
        for f in factory/candidates/ALG_*/main.py; do
          python factory/scripts/check_ast.py "$f"
        done

    - name: Pytest import check
      run: |
        pytest -q

    - name: Upload surviving candidates
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: candidates_clean
        path: factory/candidates
